name: Run Python Script on GCE

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'

      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      - name: Run bash script
        run: |
          chmod +x run_query.sh
          bash run_query.sh github-actions-testing-435312
