name: Run Python Script on GCE

on:
  workflow_dispatch:

jobs:
  start-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Start GCE VM
        run: |
          gcloud compute instances start github-test-instance --zone=us-central1-a
  
  run-script:
    needs: start-vm
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run bash script
        run: |
          chmod +x run_query.sh
          bash run_query.sh github-actions-testing-435312

  stop-vm:
    needs: run-script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Stop GCE VM
        run: |
          gcloud compute instances stop github-test-instance --zone=us-central1-a
